export const themes = new Map([
  ['myk-src', {
    '--background-color': '#1e1e2e',
    '--border-color': '#FFFFFF',
    '--text-color': '#FFFFFF',
    '--user-color': '#CCCCFF',
    '--ampersand-color': '#FFFFFF',
    '--machine-color': '#4EC9B0',
    '--path-color': '#FFC000',
    '--header-color': '#4169E1',
    '--error-color': '#FF0000',
    '--input-color': '#DAE6F0',
    '--directory-color': '#FFC000',
  }],
  ['ubuntu', {
    '--background-color': '#300A24',
    '--border-color': '#FFFFFF',
    '--text-color': '#FFFFFF',
    '--user-color': '#8AE234',
    '--ampersand-color': '#8AE234',
    '--machine-color': '#8AE234',
    '--path-color': '#729FCF',
    '--header-color': '#34E2E2',
    '--error-color': '#EF2929',
    '--input-color': '#FFFFFF',
  }],
  ['terminal', {
    '--background-color': '#111111',
    '--border-color': '#FFFFFF',
    '--text-color': '#FFFFFF',
    '--user-color': '#FFFFFF',
    '--ampersand-color': '#FFFFFF',
    '--machine-color': '#FFFFFF',
    '--path-color': '#FFFFFF',
    '--header-color': '#FFFFFF',
    '--error-color': '#FFFFFF',
    '--input-color': '#FFFFFF',
  }],
  ['matrix', {
    '--background-color': '#000000',
    '--border-color': '#FFFFFF',
    '--text-color': '#00FF00',
    '--user-color': '#00FF00',
    '--ampersand-color': '#00FF00',
    '--machine-color': '#00FF00',
    '--path-color': '#00FF00',
    '--header-color': '#00FF00',
    '--error-color': '#FF0000',
    '--input-color': '#00FF00',
  }],
  ['powershell', {
    '--background-color': '#012456',
    '--border-color': '#FFFFFF',
    '--text-color': '#FFFFFF',
    '--user-color': '#FFFFFF',
    '--ampersand-color': '#FFFFFF',
    '--machine-color': '#FFFFFF',
    '--path-color': '#FFFFFF',
    '--header-color': '#FFFFFF',
    '--error-color': '#FF0000',
    '--input-color': '#FFFF00',
  }],
  ['chrome', {
    '--background-color': '#202124',
    '--border-color': '#FFFFFF',
    '--text-color': '#FFFFFF',
    '--user-color': '#87FFC5',
    '--ampersand-color': '#87FFC5',
    '--machine-color': '#87FFC5',
    '--path-color': '#9AB3DD',
    '--header-color': '#FFFFFF',
    '--error-color': '#FF0000',
    '--input-color': '#43608E',
  }]
]);